/*

 WELCOME_BKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define welcome_bkgWidth 20
#define welcome_bkgHeight 18
#define welcome_bkgBank 0

#define welcome_bkg welcome_bkgPLN0
extern unsigned char welcome_bkgPLN0[];

/* End of WELCOME_BKG.H */
